### ISSUE TITLE
Name error in running blockParse.py

### ISSUE THREAD

**Issue by xxsabrina** [brianbeliveau/OligoMiner#6] opened 2019-08-08 17:13 UTC
Hi,

I ran

python ../OligoMiner-master/blockParse.py  -f 3.fa

and received this error:

File "blockParse.py", line 993, in <module>                                                                               main()                                                                                                                
File "blockParse.py", line 983, in main                                                                                   runSequenceCrawler(inputFile, l, L, gcPercent, GCPercent, nn_table, tm, TM,                                         NameError: name 'nn_table' is not defined

How can I fix this?

Thank you!

**Comment by brianbeliveau** [comment] 2019-08-08 18:13
Hello,

Apologies, it is difficult for me to tell what is going on without more
information. Can you please provide some more details about your
environment and any other info that might be helpful?

I can say if you are trying to pass your own variables to blockParse (eg if
you are importing it as a module into another script), the ordering of the
positional arguments in the runSequenceCrawler() command is important.

**Comment by xxsabrina** [comment] 2019-08-08 20:12
Hi Brian,
Thank you for your reply. Sorry I forgot to mention that I am just testing your scripts with your example files in Ubuntu on windows10. I am not passing my own variables to blockParse nor importing it as a module. Also I am using the Python 2.7 ver of Anaconda2.

**Comment by brianbeliveau** [comment] 2019-08-08 20:20
Hello,

Thank you for providing more information. I'm afraid I cannot replicate
this error on my end. Can you please see which packages are in your conda
environment using "conda list"? I am pasting a screenshot below of what
should be a duplicate of what you are doing and the results of 'conda list'
for my env:

[image: image.png]

**Comment by xxsabrina** [comment] 2019-08-08 20:23
Hi,
My packages are:

# Name                    Version                   Build  Channel                                                                                                                                                       _libgcc_mutex             0.1                        main                                                                                                                                                                asn1crypto                0.24.0                   pypi_0    pypi                                                                                                                                                        attrs                     19.1.0                   pypi_0    pypi                                                                                                                                                        automat                   0.7.0                    pypi_0    pypi                                                                                                                                                        bio                       0.1.0                    pypi_0    pypi                                                                                                                                                        biopython                 1.74                     pypi_0    pypi                                                                                                                                                        bowtie2                   2.3.5            py37he860b03_0    bioconda                                                                                                                                                    bzip2                     1.0.8                h516909a_0    conda-forge                                                                                                                                                 ca-certificates           2019.6.16            hecc5488_0    conda-forge                                                                                                                                                 certifi                   2019.6.16                py37_1    conda-forge                                                                                                                                                 cffi                      1.12.3                   pypi_0    pypi                                                                                                                                                        constantly                15.1.0                   pypi_0    pypi                                                                                                                                                        cryptography              2.7                      pypi_0    pypi                                                                                                                                                        cssselect                 1.0.3                    pypi_0    pypi                                                                                                                                                        hyperlink                 19.0.0                   pypi_0    pypi                                                                                                                                                        idna                      2.8                      pypi_0    pypi                                                                                                                                                        incremental               17.5.0                   pypi_0    pypi                                                                                                                                                        jellyfish                 2.2.10               h6bb024c_1    bioconda                                                                                                                                                    jemalloc                  4.5.0                         0    bioconda                                                                                                                                                    joblib                    0.13.2                   pypi_0    pypi                                                                                                                                                        libblas                   3.8.0               11_openblas    conda-forge                                                                                                                                                 libcblas                  3.8.0               11_openblas    conda-forge                                                                                                                                                 libffi                    3.2.1             he1b5a44_1006    conda-forge                                                                                                                                                 libgcc                    7.2.0                h69d50b8_2    conda-forge                                                                                                                                                 libgcc-ng                 9.1.0                hdf63c60_0                                                                                                                                                                libgfortran-ng            7.3.0                hdf63c60_0                                                                                                                                                                liblapack                 3.8.0               11_openblas    conda-forge                                                                                                                                                 libopenblas               0.3.6                h6e990d7_6    conda-forge                                                                                                                                                 libstdcxx-ng              9.1.0                hdf63c60_0                                                                                                                                                                lxml                      4.4.0                    pypi_0    pypi                                                                                                                                                        ncurses                   6.1               hf484d3e_1002    conda-forge                                                                                                                                                 numpy                     1.17.0           py37h95a1406_0    conda-forge                                                                                                                                                 openssl                   1.1.1c               h516909a_0    conda-forge                                                                                                                                                 parsel                    1.5.1                    pypi_0    pypi                                                                                                                                                        perl                      5.26.2            h516909a_1006    conda-forge                                                                                                                                                 pip                       19.2.1                   py37_0    conda-forge                                                                                                                                                 pyasn1                    0.4.6                    pypi_0    pypi                                                                                                                                                        pyasn1-modules            0.2.6                    pypi_0    pypi                                                                                                                                                        pycparser                 2.19                     pypi_0    pypi                                                                                                                                                        pydispatcher              2.0.5                    pypi_0    pypi                                                                                                                                                        pyhamcrest                1.9.0                    pypi_0    pypi                                                                                                                                                        pyopenssl                 19.0.0                   pypi_0    pypi                                                                                                                                                        python                    3.7.3                h33d41f4_1    conda-forge                                                                                                                                                 queuelib                  1.5.0                    pypi_0    pypi                                                                                                                                                        readline                  8.0                  hf8c457e_0    conda-forge                                                                                                                                                 regex                     2019.6.8                 pypi_0    pypi                                                                                                                                                        scikit-learn              0.21.3           py37hcdab131_0    conda-forge                                                                                                                                                 scipy                     1.3.0                    pypi_0    pypi                                                                                                                                                        scrapy                    1.7.3                    pypi_0    pypi                                                                                                                                                        service-identity          18.1.0                   pypi_0    pypi                                                                                                                                                        setuptools                41.0.1                   py37_0    conda-forge                                                                                                                                                 six                       1.12.0                   pypi_0    pypi                                                                                                                                                        sqlite                    3.29.0               hcee41ef_0    conda-forge                                                                                                                                                 tbb                       2019.7               hc9558a2_0    conda-forge                                                                                                                                                 tk                        8.6.9             hed695b0_1002    conda-forge                                                                                                                                                 twisted                   19.7.0                   pypi_0    pypi                                                                                                                                                        w3lib                     1.20.0                   pypi_0    pypi                                                                                                                                                        wheel                     0.33.4                   py37_0    conda-forge                                                                                                                                                 xz                        5.2.4             h14c3975_1001    conda-forge                                                                                                                                                 zlib                      1.2.11            h516909a_1005    conda-forge                                                                                                                                                 zope-interface            4.6.0                    pypi_0    pypi

**Comment by brianbeliveau** [comment] 2019-08-08 20:32
Hello,

Can you please provide me with the exact command you used to create your
conda environment? It is possible a version difference of on the packages
could be the issue. Thanks

**Comment by xxsabrina** [comment] 2019-08-08 20:40
Hi,

I think I just did the regular conda create --name probemining. Then I installed the packages by pip using pip install.

**Comment by xxsabrina** [comment] 2019-08-08 20:56
Hi Brian,
I just had a check of my Python version and surprised to find it's actually 3.7. I thought it was 2.7. Maybe this is the problem?

**Comment by brianbeliveau** [comment] 2019-08-08 21:03
Hello,

Yes, that would be a problem, although I would expect the error the script
would throw would be different (invalid syntax on a 'print' statement')

Can you please try making a new conda environment with this command: conda
create --name pm_test numpy scipy biopython scikit-learn python=2.7.12

I just made a brand-new env with that command and can still run blockParse
without issue. You can of course give the env a different name if you'd
prefer.

**Comment by xxsabrina** [comment] 2019-08-08 21:14
Hi,
I did exactly what you said. And got the following error:
(pm_test) user@**********:~/OligoMiner-master$ python blockParse.py -f 3.fa                                        Traceback (most recent call last):                                                                                        File "blockParse.py", line 47, in <module>                                                                                from Bio.SeqUtils import MeltingTemp as mt                                                                          ImportError: No module named Bio.SeqUtils

**Comment by brianbeliveau** [comment] 2019-08-08 21:31
It seems like your interpreter is not able to find your Biopython install.
I am not sure why. I would recommend uninstalling and re-installing
Anaconda, then trying the environment creation command from my last message
again.

**Comment by xxsabrina** [comment] 2019-08-09 14:04
Hi,
I tried to uninstall and re-install anaconda. Now everything is working! Thank you so much!

**Closed** 2019-08-09 18:33 UTC
